export {default as Navbar} from './Navbar/Navbar';
export {default as Home} from './Home/Home';
export {default as CallButton} from './CallButton/CallButton';
export {default as ProductList} from './Product/ProductList';
export {default as Support} from './Support/Support';
export {default as Policies} from './Policies/Policies';
export {default as Contact} from './Contact/Contact';
export {default as About} from './About/About';
export {default as ProductDetail} from './Product/ProductDetail';
